/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.records;


import br.com.rodrigocardoso.database.tables.Doacao;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoacaoRecord extends UpdatableRecordImpl<DoacaoRecord> implements Record10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, Double, UUID, UUID> {

    private static final long serialVersionUID = -993978213;

    /**
     * Setter for <code>public.doacao.created_date</code>.
     */
    public DoacaoRecord setCreatedDate(Timestamp value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.doacao.created_user</code>.
     */
    public DoacaoRecord setCreatedUser(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.created_user</code>.
     */
    public UUID getCreatedUser() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.doacao.updated_date</code>.
     */
    public DoacaoRecord setUpdatedDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.updated_date</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.doacao.updated_user</code>.
     */
    public DoacaoRecord setUpdatedUser(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.updated_user</code>.
     */
    public UUID getUpdatedUser() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.doacao.active</code>.
     */
    public DoacaoRecord setActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.doacao.id</code>.
     */
    public DoacaoRecord setId(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.id</code>.
     */
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.doacao.descricao</code>.
     */
    public DoacaoRecord setDescricao(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.descricao</code>.
     */
    public String getDescricao() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.doacao.valor</code>.
     */
    public DoacaoRecord setValor(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.valor</code>.
     */
    public Double getValor() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.doacao.pessoa_id</code>.
     */
    public DoacaoRecord setPessoaId(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.pessoa_id</code>.
     */
    public UUID getPessoaId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.doacao.venda_dia_id</code>.
     */
    public DoacaoRecord setVendaDiaId(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.doacao.venda_dia_id</code>.
     */
    public UUID getVendaDiaId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, Double, UUID, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, Double, UUID, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return Doacao.DOACAO.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Doacao.DOACAO.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Doacao.DOACAO.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Doacao.DOACAO.UPDATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Doacao.DOACAO.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return Doacao.DOACAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Doacao.DOACAO.DESCRICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Doacao.DOACAO.VALOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field9() {
        return Doacao.DOACAO.PESSOA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field10() {
        return Doacao.DOACAO.VENDA_DIA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getValor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component9() {
        return getPessoaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component10() {
        return getVendaDiaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getValor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value9() {
        return getPessoaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value10() {
        return getVendaDiaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value1(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value2(UUID value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value3(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value4(UUID value) {
        setUpdatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value6(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value7(String value) {
        setDescricao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value8(Double value) {
        setValor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value9(UUID value) {
        setPessoaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord value10(UUID value) {
        setVendaDiaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoacaoRecord values(Timestamp value1, UUID value2, Timestamp value3, UUID value4, Boolean value5, UUID value6, String value7, Double value8, UUID value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DoacaoRecord
     */
    public DoacaoRecord() {
        super(Doacao.DOACAO);
    }

    /**
     * Create a detached, initialised DoacaoRecord
     */
    public DoacaoRecord(Timestamp createdDate, UUID createdUser, Timestamp updatedDate, UUID updatedUser, Boolean active, UUID id, String descricao, Double valor, UUID pessoaId, UUID vendaDiaId) {
        super(Doacao.DOACAO);

        set(0, createdDate);
        set(1, createdUser);
        set(2, updatedDate);
        set(3, updatedUser);
        set(4, active);
        set(5, id);
        set(6, descricao);
        set(7, valor);
        set(8, pessoaId);
        set(9, vendaDiaId);
    }
}
