/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.records;


import br.com.rodrigocardoso.database.enums.TipoPessoas;
import br.com.rodrigocardoso.database.tables.Pessoa;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PessoaRecord extends UpdatableRecordImpl<PessoaRecord> implements Record9<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, String, TipoPessoas> {

    private static final long serialVersionUID = -632268998;

    /**
     * Setter for <code>public.pessoa.created_date</code>.
     */
    public PessoaRecord setCreatedDate(Timestamp value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.pessoa.created_user</code>.
     */
    public PessoaRecord setCreatedUser(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.created_user</code>.
     */
    public UUID getCreatedUser() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.pessoa.updated_date</code>.
     */
    public PessoaRecord setUpdatedDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.updated_date</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.pessoa.updated_user</code>.
     */
    public PessoaRecord setUpdatedUser(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.updated_user</code>.
     */
    public UUID getUpdatedUser() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.pessoa.active</code>.
     */
    public PessoaRecord setActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.pessoa.id</code>.
     */
    public PessoaRecord setId(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.id</code>.
     */
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.pessoa.nome</code>.
     */
    public PessoaRecord setNome(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.nome</code>.
     */
    public String getNome() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.pessoa.telefone</code>.
     */
    public PessoaRecord setTelefone(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.telefone</code>.
     */
    public String getTelefone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.pessoa.pessoa</code>.
     */
    public PessoaRecord setPessoa(TipoPessoas value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.pessoa.pessoa</code>.
     */
    public TipoPessoas getPessoa() {
        return (TipoPessoas) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, String, TipoPessoas> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, String, String, TipoPessoas> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return Pessoa.PESSOA.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Pessoa.PESSOA.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Pessoa.PESSOA.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Pessoa.PESSOA.UPDATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Pessoa.PESSOA.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return Pessoa.PESSOA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Pessoa.PESSOA.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Pessoa.PESSOA.TELEFONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TipoPessoas> field9() {
        return Pessoa.PESSOA.PESSOA_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TipoPessoas component9() {
        return getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TipoPessoas value9() {
        return getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value1(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value2(UUID value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value3(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value4(UUID value) {
        setUpdatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value6(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value7(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value8(String value) {
        setTelefone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value9(TipoPessoas value) {
        setPessoa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord values(Timestamp value1, UUID value2, Timestamp value3, UUID value4, Boolean value5, UUID value6, String value7, String value8, TipoPessoas value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PessoaRecord
     */
    public PessoaRecord() {
        super(Pessoa.PESSOA);
    }

    /**
     * Create a detached, initialised PessoaRecord
     */
    public PessoaRecord(Timestamp createdDate, UUID createdUser, Timestamp updatedDate, UUID updatedUser, Boolean active, UUID id, String nome, String telefone, TipoPessoas pessoa) {
        super(Pessoa.PESSOA);

        set(0, createdDate);
        set(1, createdUser);
        set(2, updatedDate);
        set(3, updatedUser);
        set(4, active);
        set(5, id);
        set(6, nome);
        set(7, telefone);
        set(8, pessoa);
    }
}
