/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.records;


import br.com.rodrigocardoso.database.tables.VendaProduto;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaProdutoRecord extends UpdatableRecordImpl<VendaProdutoRecord> implements Record10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, Double, Integer, UUID, UUID> {

    private static final long serialVersionUID = -1445935353;

    /**
     * Setter for <code>public.venda_produto.created_date</code>.
     */
    public VendaProdutoRecord setCreatedDate(Timestamp value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.venda_produto.created_user</code>.
     */
    public VendaProdutoRecord setCreatedUser(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.created_user</code>.
     */
    public UUID getCreatedUser() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.venda_produto.updated_date</code>.
     */
    public VendaProdutoRecord setUpdatedDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.updated_date</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.venda_produto.updated_user</code>.
     */
    public VendaProdutoRecord setUpdatedUser(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.updated_user</code>.
     */
    public UUID getUpdatedUser() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.venda_produto.active</code>.
     */
    public VendaProdutoRecord setActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.venda_produto.id</code>.
     */
    public VendaProdutoRecord setId(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.id</code>.
     */
    public UUID getId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.venda_produto.valor_unitario</code>.
     */
    public VendaProdutoRecord setValorUnitario(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.valor_unitario</code>.
     */
    public Double getValorUnitario() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.venda_produto.quantidade</code>.
     */
    public VendaProdutoRecord setQuantidade(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.quantidade</code>.
     */
    public Integer getQuantidade() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.venda_produto.produto_id</code>.
     */
    public VendaProdutoRecord setProdutoId(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.produto_id</code>.
     */
    public UUID getProdutoId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.venda_produto.venda_id</code>.
     */
    public VendaProdutoRecord setVendaId(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.venda_produto.venda_id</code>.
     */
    public UUID getVendaId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, Double, Integer, UUID, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Timestamp, UUID, Timestamp, UUID, Boolean, UUID, Double, Integer, UUID, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return VendaProduto.VENDA_PRODUTO.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return VendaProduto.VENDA_PRODUTO.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VendaProduto.VENDA_PRODUTO.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return VendaProduto.VENDA_PRODUTO.UPDATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return VendaProduto.VENDA_PRODUTO.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return VendaProduto.VENDA_PRODUTO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return VendaProduto.VENDA_PRODUTO.VALOR_UNITARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VendaProduto.VENDA_PRODUTO.QUANTIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field9() {
        return VendaProduto.VENDA_PRODUTO.PRODUTO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field10() {
        return VendaProduto.VENDA_PRODUTO.VENDA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getValorUnitario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component9() {
        return getProdutoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component10() {
        return getVendaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getUpdatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getValorUnitario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value9() {
        return getProdutoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value10() {
        return getVendaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value1(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value2(UUID value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value3(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value4(UUID value) {
        setUpdatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value6(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value7(Double value) {
        setValorUnitario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value8(Integer value) {
        setQuantidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value9(UUID value) {
        setProdutoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord value10(UUID value) {
        setVendaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaProdutoRecord values(Timestamp value1, UUID value2, Timestamp value3, UUID value4, Boolean value5, UUID value6, Double value7, Integer value8, UUID value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendaProdutoRecord
     */
    public VendaProdutoRecord() {
        super(VendaProduto.VENDA_PRODUTO);
    }

    /**
     * Create a detached, initialised VendaProdutoRecord
     */
    public VendaProdutoRecord(Timestamp createdDate, UUID createdUser, Timestamp updatedDate, UUID updatedUser, Boolean active, UUID id, Double valorUnitario, Integer quantidade, UUID produtoId, UUID vendaId) {
        super(VendaProduto.VENDA_PRODUTO);

        set(0, createdDate);
        set(1, createdUser);
        set(2, updatedDate);
        set(3, updatedUser);
        set(4, active);
        set(5, id);
        set(6, valorUnitario);
        set(7, quantidade);
        set(8, produtoId);
        set(9, vendaId);
    }
}
