/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.tables.records.CategoriaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categoria extends TableImpl<CategoriaRecord> {

    private static final long serialVersionUID = -1535177465;

    /**
     * The reference instance of <code>public.categoria</code>
     */
    public static final Categoria CATEGORIA = new Categoria();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoriaRecord> getRecordType() {
        return CategoriaRecord.class;
    }

    /**
     * The column <code>public.categoria.created_date</code>.
     */
    public final TableField<CategoriaRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.categoria.created_user</code>.
     */
    public final TableField<CategoriaRecord, UUID> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.categoria.updated_date</code>.
     */
    public final TableField<CategoriaRecord, Timestamp> UPDATED_DATE = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.categoria.updated_user</code>.
     */
    public final TableField<CategoriaRecord, UUID> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.categoria.active</code>.
     */
    public final TableField<CategoriaRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.categoria.id</code>.
     */
    public final TableField<CategoriaRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.categoria.descricao</code>.
     */
    public final TableField<CategoriaRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>public.categoria</code> table reference
     */
    public Categoria() {
        this(DSL.name("categoria"), null);
    }

    /**
     * Create an aliased <code>public.categoria</code> table reference
     */
    public Categoria(String alias) {
        this(DSL.name(alias), CATEGORIA);
    }

    /**
     * Create an aliased <code>public.categoria</code> table reference
     */
    public Categoria(Name alias) {
        this(alias, CATEGORIA);
    }

    private Categoria(Name alias, Table<CategoriaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Categoria(Name alias, Table<CategoriaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CATEGORIA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategoriaRecord> getPrimaryKey() {
        return Keys.CATEGORIA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategoriaRecord>> getKeys() {
        return Arrays.<UniqueKey<CategoriaRecord>>asList(Keys.CATEGORIA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Categoria as(String alias) {
        return new Categoria(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Categoria as(Name alias) {
        return new Categoria(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Categoria rename(String name) {
        return new Categoria(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Categoria rename(Name name) {
        return new Categoria(name, null);
    }
}
