/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.tables.records.DividaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Divida extends TableImpl<DividaRecord> {

    private static final long serialVersionUID = -910554185;

    /**
     * The reference instance of <code>public.divida</code>
     */
    public static final Divida DIVIDA = new Divida();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DividaRecord> getRecordType() {
        return DividaRecord.class;
    }

    /**
     * The column <code>public.divida.created_date</code>.
     */
    public final TableField<DividaRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.divida.created_user</code>.
     */
    public final TableField<DividaRecord, UUID> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.divida.updated_date</code>.
     */
    public final TableField<DividaRecord, Timestamp> UPDATED_DATE = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.divida.updated_user</code>.
     */
    public final TableField<DividaRecord, UUID> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.divida.active</code>.
     */
    public final TableField<DividaRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.divida.id</code>.
     */
    public final TableField<DividaRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.divida.descricao</code>.
     */
    public final TableField<DividaRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.divida.valor</code>.
     */
    public final TableField<DividaRecord, Double> VALOR = createField("valor", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.divida.data</code>.
     */
    public final TableField<DividaRecord, Timestamp> DATA = createField("data", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.divida.pessoa_id</code>.
     */
    public final TableField<DividaRecord, UUID> PESSOA_ID = createField("pessoa_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * Create a <code>public.divida</code> table reference
     */
    public Divida() {
        this(DSL.name("divida"), null);
    }

    /**
     * Create an aliased <code>public.divida</code> table reference
     */
    public Divida(String alias) {
        this(DSL.name(alias), DIVIDA);
    }

    /**
     * Create an aliased <code>public.divida</code> table reference
     */
    public Divida(Name alias) {
        this(alias, DIVIDA);
    }

    private Divida(Name alias, Table<DividaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Divida(Name alias, Table<DividaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DIVIDA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DividaRecord> getPrimaryKey() {
        return Keys.DIVIDA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DividaRecord>> getKeys() {
        return Arrays.<UniqueKey<DividaRecord>>asList(Keys.DIVIDA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DividaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DividaRecord, ?>>asList(Keys.DIVIDA__DIVIDA_PESSOA_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Divida as(String alias) {
        return new Divida(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Divida as(Name alias) {
        return new Divida(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Divida rename(String name) {
        return new Divida(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Divida rename(Name name) {
        return new Divida(name, null);
    }
}
