/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.tables.records.DoacaoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doacao extends TableImpl<DoacaoRecord> {

    private static final long serialVersionUID = -1122325588;

    /**
     * The reference instance of <code>public.doacao</code>
     */
    public static final Doacao DOACAO = new Doacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoacaoRecord> getRecordType() {
        return DoacaoRecord.class;
    }

    /**
     * The column <code>public.doacao.created_date</code>.
     */
    public final TableField<DoacaoRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.doacao.created_user</code>.
     */
    public final TableField<DoacaoRecord, UUID> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.doacao.updated_date</code>.
     */
    public final TableField<DoacaoRecord, Timestamp> UPDATED_DATE = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.doacao.updated_user</code>.
     */
    public final TableField<DoacaoRecord, UUID> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doacao.active</code>.
     */
    public final TableField<DoacaoRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.doacao.id</code>.
     */
    public final TableField<DoacaoRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.doacao.descricao</code>.
     */
    public final TableField<DoacaoRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.doacao.valor</code>.
     */
    public final TableField<DoacaoRecord, Double> VALOR = createField("valor", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.doacao.pessoa_id</code>.
     */
    public final TableField<DoacaoRecord, UUID> PESSOA_ID = createField("pessoa_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.doacao.venda_dia_id</code>.
     */
    public final TableField<DoacaoRecord, UUID> VENDA_DIA_ID = createField("venda_dia_id", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * Create a <code>public.doacao</code> table reference
     */
    public Doacao() {
        this(DSL.name("doacao"), null);
    }

    /**
     * Create an aliased <code>public.doacao</code> table reference
     */
    public Doacao(String alias) {
        this(DSL.name(alias), DOACAO);
    }

    /**
     * Create an aliased <code>public.doacao</code> table reference
     */
    public Doacao(Name alias) {
        this(alias, DOACAO);
    }

    private Doacao(Name alias, Table<DoacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Doacao(Name alias, Table<DoacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DOACAO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DoacaoRecord> getPrimaryKey() {
        return Keys.DOACAO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DoacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<DoacaoRecord>>asList(Keys.DOACAO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DoacaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DoacaoRecord, ?>>asList(Keys.DOACAO__DOACAO_PESSOA_ID_FKEY, Keys.DOACAO__DOACAO_VENDA_DIA_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doacao as(String alias) {
        return new Doacao(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Doacao as(Name alias) {
        return new Doacao(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Doacao rename(String name) {
        return new Doacao(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Doacao rename(Name name) {
        return new Doacao(name, null);
    }
}
