/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.tables.records.ProdutoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Produto extends TableImpl<ProdutoRecord> {

    private static final long serialVersionUID = 1993872253;

    /**
     * The reference instance of <code>public.produto</code>
     */
    public static final Produto PRODUTO = new Produto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProdutoRecord> getRecordType() {
        return ProdutoRecord.class;
    }

    /**
     * The column <code>public.produto.created_date</code>.
     */
    public final TableField<ProdutoRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.produto.created_user</code>.
     */
    public final TableField<ProdutoRecord, UUID> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.produto.updated_date</code>.
     */
    public final TableField<ProdutoRecord, Timestamp> UPDATED_DATE = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.produto.updated_user</code>.
     */
    public final TableField<ProdutoRecord, UUID> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.produto.active</code>.
     */
    public final TableField<ProdutoRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.produto.id</code>.
     */
    public final TableField<ProdutoRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.produto.descricao</code>.
     */
    public final TableField<ProdutoRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.produto.codigo</code>.
     */
    public final TableField<ProdutoRecord, String> CODIGO = createField("codigo", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.produto.valor</code>.
     */
    public final TableField<ProdutoRecord, Double> VALOR = createField("valor", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.produto.categoria_id</code>.
     */
    public final TableField<ProdutoRecord, UUID> CATEGORIA_ID = createField("categoria_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * Create a <code>public.produto</code> table reference
     */
    public Produto() {
        this(DSL.name("produto"), null);
    }

    /**
     * Create an aliased <code>public.produto</code> table reference
     */
    public Produto(String alias) {
        this(DSL.name(alias), PRODUTO);
    }

    /**
     * Create an aliased <code>public.produto</code> table reference
     */
    public Produto(Name alias) {
        this(alias, PRODUTO);
    }

    private Produto(Name alias, Table<ProdutoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Produto(Name alias, Table<ProdutoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUTO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProdutoRecord> getPrimaryKey() {
        return Keys.PRODUTO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProdutoRecord>> getKeys() {
        return Arrays.<UniqueKey<ProdutoRecord>>asList(Keys.PRODUTO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProdutoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProdutoRecord, ?>>asList(Keys.PRODUTO__PRODUTO_CATEGORIA_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Produto as(String alias) {
        return new Produto(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Produto as(Name alias) {
        return new Produto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Produto rename(String name) {
        return new Produto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Produto rename(Name name) {
        return new Produto(name, null);
    }
}
