/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.enums.StatusVendaDia;
import br.com.rodrigocardoso.database.tables.records.VendaDiaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaDia extends TableImpl<VendaDiaRecord> {

    private static final long serialVersionUID = -1504695531;

    /**
     * The reference instance of <code>public.venda_dia</code>
     */
    public static final VendaDia VENDA_DIA = new VendaDia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VendaDiaRecord> getRecordType() {
        return VendaDiaRecord.class;
    }

    /**
     * The column <code>public.venda_dia.created_date</code>.
     */
    public final TableField<VendaDiaRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.venda_dia.created_user</code>.
     */
    public final TableField<VendaDiaRecord, UUID> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.venda_dia.updated_date</code>.
     */
    public final TableField<VendaDiaRecord, Timestamp> UPDATED_DATE = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.venda_dia.updated_user</code>.
     */
    public final TableField<VendaDiaRecord, UUID> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.venda_dia.active</code>.
     */
    public final TableField<VendaDiaRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.venda_dia.id</code>.
     */
    public final TableField<VendaDiaRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.venda_dia.data</code>.
     */
    public final TableField<VendaDiaRecord, Timestamp> DATA = createField("data", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.venda_dia.valor_abertura</code>.
     */
    public final TableField<VendaDiaRecord, Double> VALOR_ABERTURA = createField("valor_abertura", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.venda_dia.valor_fechamento</code>.
     */
    public final TableField<VendaDiaRecord, Double> VALOR_FECHAMENTO = createField("valor_fechamento", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.venda_dia.status</code>.
     */
    public final TableField<VendaDiaRecord, StatusVendaDia> STATUS = createField("status", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(br.com.rodrigocardoso.database.enums.StatusVendaDia.class), this, "");

    /**
     * The column <code>public.venda_dia.motivo_cancelamento</code>.
     */
    public final TableField<VendaDiaRecord, String> MOTIVO_CANCELAMENTO = createField("motivo_cancelamento", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.venda_dia</code> table reference
     */
    public VendaDia() {
        this(DSL.name("venda_dia"), null);
    }

    /**
     * Create an aliased <code>public.venda_dia</code> table reference
     */
    public VendaDia(String alias) {
        this(DSL.name(alias), VENDA_DIA);
    }

    /**
     * Create an aliased <code>public.venda_dia</code> table reference
     */
    public VendaDia(Name alias) {
        this(alias, VENDA_DIA);
    }

    private VendaDia(Name alias, Table<VendaDiaRecord> aliased) {
        this(alias, aliased, null);
    }

    private VendaDia(Name alias, Table<VendaDiaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VENDA_DIA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VendaDiaRecord> getPrimaryKey() {
        return Keys.VENDA_DIA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VendaDiaRecord>> getKeys() {
        return Arrays.<UniqueKey<VendaDiaRecord>>asList(Keys.VENDA_DIA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaDia as(String alias) {
        return new VendaDia(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VendaDia as(Name alias) {
        return new VendaDia(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VendaDia rename(String name) {
        return new VendaDia(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VendaDia rename(Name name) {
        return new VendaDia(name, null);
    }
}
