/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categoria implements Serializable {

    private static final long serialVersionUID = 1890029779;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private String    descricao;

    public Categoria() {}

    public Categoria(Categoria value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.descricao = value.descricao;
    }

    public Categoria(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        String    descricao
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.descricao = descricao;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Categoria setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Categoria setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Categoria setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Categoria setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Categoria setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Categoria setId(UUID id) {
        this.id = id;
        return this;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public Categoria setDescricao(String descricao) {
        this.descricao = descricao;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Categoria (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(descricao);

        sb.append(")");
        return sb.toString();
    }
}
