/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doacao implements Serializable {

    private static final long serialVersionUID = 109335584;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private String    descricao;
    private Double    valor;
    private UUID      pessoaId;
    private UUID      vendaDiaId;

    public Doacao() {}

    public Doacao(Doacao value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.descricao = value.descricao;
        this.valor = value.valor;
        this.pessoaId = value.pessoaId;
        this.vendaDiaId = value.vendaDiaId;
    }

    public Doacao(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        String    descricao,
        Double    valor,
        UUID      pessoaId,
        UUID      vendaDiaId
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.descricao = descricao;
        this.valor = valor;
        this.pessoaId = pessoaId;
        this.vendaDiaId = vendaDiaId;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Doacao setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Doacao setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Doacao setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Doacao setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Doacao setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Doacao setId(UUID id) {
        this.id = id;
        return this;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public Doacao setDescricao(String descricao) {
        this.descricao = descricao;
        return this;
    }

    public Double getValor() {
        return this.valor;
    }

    public Doacao setValor(Double valor) {
        this.valor = valor;
        return this;
    }

    public UUID getPessoaId() {
        return this.pessoaId;
    }

    public Doacao setPessoaId(UUID pessoaId) {
        this.pessoaId = pessoaId;
        return this;
    }

    public UUID getVendaDiaId() {
        return this.vendaDiaId;
    }

    public Doacao setVendaDiaId(UUID vendaDiaId) {
        this.vendaDiaId = vendaDiaId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Doacao (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(descricao);
        sb.append(", ").append(valor);
        sb.append(", ").append(pessoaId);
        sb.append(", ").append(vendaDiaId);

        sb.append(")");
        return sb.toString();
    }
}
