/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entidade implements Serializable {

    private static final long serialVersionUID = 2093501876;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;

    public Entidade() {}

    public Entidade(Entidade value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
    }

    public Entidade(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Entidade setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Entidade setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Entidade setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Entidade setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Entidade setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entidade (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
