/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pagamento implements Serializable {

    private static final long serialVersionUID = 932788833;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private String    descricao;
    private Double    valor;
    private Timestamp data;
    private UUID      pessoaId;

    public Pagamento() {}

    public Pagamento(Pagamento value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.descricao = value.descricao;
        this.valor = value.valor;
        this.data = value.data;
        this.pessoaId = value.pessoaId;
    }

    public Pagamento(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        String    descricao,
        Double    valor,
        Timestamp data,
        UUID      pessoaId
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.descricao = descricao;
        this.valor = valor;
        this.data = data;
        this.pessoaId = pessoaId;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Pagamento setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Pagamento setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Pagamento setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Pagamento setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Pagamento setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Pagamento setId(UUID id) {
        this.id = id;
        return this;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public Pagamento setDescricao(String descricao) {
        this.descricao = descricao;
        return this;
    }

    public Double getValor() {
        return this.valor;
    }

    public Pagamento setValor(Double valor) {
        this.valor = valor;
        return this;
    }

    public Timestamp getData() {
        return this.data;
    }

    public Pagamento setData(Timestamp data) {
        this.data = data;
        return this;
    }

    public UUID getPessoaId() {
        return this.pessoaId;
    }

    public Pagamento setPessoaId(UUID pessoaId) {
        this.pessoaId = pessoaId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pagamento (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(descricao);
        sb.append(", ").append(valor);
        sb.append(", ").append(data);
        sb.append(", ").append(pessoaId);

        sb.append(")");
        return sb.toString();
    }
}
