/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import br.com.rodrigocardoso.database.enums.TipoPessoas;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pessoa implements Serializable {

    private static final long serialVersionUID = 956841791;

    private Timestamp   createdDate;
    private UUID        createdUser;
    private Timestamp   updatedDate;
    private UUID        updatedUser;
    private Boolean     active;
    private UUID        id;
    private String      nome;
    private String      telefone;
    private TipoPessoas pessoa;

    public Pessoa() {}

    public Pessoa(Pessoa value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.nome = value.nome;
        this.telefone = value.telefone;
        this.pessoa = value.pessoa;
    }

    public Pessoa(
        Timestamp   createdDate,
        UUID        createdUser,
        Timestamp   updatedDate,
        UUID        updatedUser,
        Boolean     active,
        UUID        id,
        String      nome,
        String      telefone,
        TipoPessoas pessoa
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.nome = nome;
        this.telefone = telefone;
        this.pessoa = pessoa;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Pessoa setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Pessoa setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Pessoa setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Pessoa setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Pessoa setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Pessoa setId(UUID id) {
        this.id = id;
        return this;
    }

    public String getNome() {
        return this.nome;
    }

    public Pessoa setNome(String nome) {
        this.nome = nome;
        return this;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public Pessoa setTelefone(String telefone) {
        this.telefone = telefone;
        return this;
    }

    public TipoPessoas getPessoa() {
        return this.pessoa;
    }

    public Pessoa setPessoa(TipoPessoas pessoa) {
        this.pessoa = pessoa;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pessoa (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(nome);
        sb.append(", ").append(telefone);
        sb.append(", ").append(pessoa);

        sb.append(")");
        return sb.toString();
    }
}
