/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuario implements Serializable {

    private static final long serialVersionUID = -1404942825;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private String    nome;
    private String    email;
    private String    senha;
    private String    salt;
    private String    userToken;

    public Usuario() {}

    public Usuario(Usuario value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.nome = value.nome;
        this.email = value.email;
        this.senha = value.senha;
        this.salt = value.salt;
        this.userToken = value.userToken;
    }

    public Usuario(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        String    nome,
        String    email,
        String    senha,
        String    salt,
        String    userToken
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.salt = salt;
        this.userToken = userToken;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Usuario setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Usuario setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Usuario setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Usuario setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Usuario setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Usuario setId(UUID id) {
        this.id = id;
        return this;
    }

    public String getNome() {
        return this.nome;
    }

    public Usuario setNome(String nome) {
        this.nome = nome;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Usuario setEmail(String email) {
        this.email = email;
        return this;
    }

    public String getSenha() {
        return this.senha;
    }

    public Usuario setSenha(String senha) {
        this.senha = senha;
        return this;
    }

    public String getSalt() {
        return this.salt;
    }

    public Usuario setSalt(String salt) {
        this.salt = salt;
        return this;
    }

    public String getUserToken() {
        return this.userToken;
    }

    public Usuario setUserToken(String userToken) {
        this.userToken = userToken;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usuario (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(nome);
        sb.append(", ").append(email);
        sb.append(", ").append(senha);
        sb.append(", ").append(salt);
        sb.append(", ").append(userToken);

        sb.append(")");
        return sb.toString();
    }
}
