/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import br.com.rodrigocardoso.database.enums.StatusVendaDia;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaDia implements Serializable {

    private static final long serialVersionUID = 974427300;

    private Timestamp      createdDate;
    private UUID           createdUser;
    private Timestamp      updatedDate;
    private UUID           updatedUser;
    private Boolean        active;
    private UUID           id;
    private Timestamp      data;
    private Double         valorAbertura;
    private Double         valorFechamento;
    private StatusVendaDia status;
    private String         motivoCancelamento;

    public VendaDia() {}

    public VendaDia(VendaDia value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.data = value.data;
        this.valorAbertura = value.valorAbertura;
        this.valorFechamento = value.valorFechamento;
        this.status = value.status;
        this.motivoCancelamento = value.motivoCancelamento;
    }

    public VendaDia(
        Timestamp      createdDate,
        UUID           createdUser,
        Timestamp      updatedDate,
        UUID           updatedUser,
        Boolean        active,
        UUID           id,
        Timestamp      data,
        Double         valorAbertura,
        Double         valorFechamento,
        StatusVendaDia status,
        String         motivoCancelamento
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.data = data;
        this.valorAbertura = valorAbertura;
        this.valorFechamento = valorFechamento;
        this.status = status;
        this.motivoCancelamento = motivoCancelamento;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public VendaDia setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public VendaDia setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public VendaDia setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public VendaDia setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public VendaDia setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public VendaDia setId(UUID id) {
        this.id = id;
        return this;
    }

    public Timestamp getData() {
        return this.data;
    }

    public VendaDia setData(Timestamp data) {
        this.data = data;
        return this;
    }

    public Double getValorAbertura() {
        return this.valorAbertura;
    }

    public VendaDia setValorAbertura(Double valorAbertura) {
        this.valorAbertura = valorAbertura;
        return this;
    }

    public Double getValorFechamento() {
        return this.valorFechamento;
    }

    public VendaDia setValorFechamento(Double valorFechamento) {
        this.valorFechamento = valorFechamento;
        return this;
    }

    public StatusVendaDia getStatus() {
        return this.status;
    }

    public VendaDia setStatus(StatusVendaDia status) {
        this.status = status;
        return this;
    }

    public String getMotivoCancelamento() {
        return this.motivoCancelamento;
    }

    public VendaDia setMotivoCancelamento(String motivoCancelamento) {
        this.motivoCancelamento = motivoCancelamento;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VendaDia (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(data);
        sb.append(", ").append(valorAbertura);
        sb.append(", ").append(valorFechamento);
        sb.append(", ").append(status);
        sb.append(", ").append(motivoCancelamento);

        sb.append(")");
        return sb.toString();
    }
}
