/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaProduto implements Serializable {

    private static final long serialVersionUID = -1407621678;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private Double    valorUnitario;
    private Integer   quantidade;
    private UUID      produtoId;
    private UUID      vendaId;

    public VendaProduto() {}

    public VendaProduto(VendaProduto value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.valorUnitario = value.valorUnitario;
        this.quantidade = value.quantidade;
        this.produtoId = value.produtoId;
        this.vendaId = value.vendaId;
    }

    public VendaProduto(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        Double    valorUnitario,
        Integer   quantidade,
        UUID      produtoId,
        UUID      vendaId
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.valorUnitario = valorUnitario;
        this.quantidade = quantidade;
        this.produtoId = produtoId;
        this.vendaId = vendaId;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public VendaProduto setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public VendaProduto setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public VendaProduto setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public VendaProduto setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public VendaProduto setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public VendaProduto setId(UUID id) {
        this.id = id;
        return this;
    }

    public Double getValorUnitario() {
        return this.valorUnitario;
    }

    public VendaProduto setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
        return this;
    }

    public Integer getQuantidade() {
        return this.quantidade;
    }

    public VendaProduto setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
        return this;
    }

    public UUID getProdutoId() {
        return this.produtoId;
    }

    public VendaProduto setProdutoId(UUID produtoId) {
        this.produtoId = produtoId;
        return this;
    }

    public UUID getVendaId() {
        return this.vendaId;
    }

    public VendaProduto setVendaId(UUID vendaId) {
        this.vendaId = vendaId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VendaProduto (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(valorUnitario);
        sb.append(", ").append(quantidade);
        sb.append(", ").append(produtoId);
        sb.append(", ").append(vendaId);

        sb.append(")");
        return sb.toString();
    }
}
