/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Venda implements Serializable {

    private static final long serialVersionUID = -1386985655;

    private Timestamp createdDate;
    private UUID      createdUser;
    private Timestamp updatedDate;
    private UUID      updatedUser;
    private Boolean   active;
    private UUID      id;
    private UUID      vendaDiaId;
    private UUID      pessoaId;

    public Venda() {}

    public Venda(Venda value) {
        this.createdDate = value.createdDate;
        this.createdUser = value.createdUser;
        this.updatedDate = value.updatedDate;
        this.updatedUser = value.updatedUser;
        this.active = value.active;
        this.id = value.id;
        this.vendaDiaId = value.vendaDiaId;
        this.pessoaId = value.pessoaId;
    }

    public Venda(
        Timestamp createdDate,
        UUID      createdUser,
        Timestamp updatedDate,
        UUID      updatedUser,
        Boolean   active,
        UUID      id,
        UUID      vendaDiaId,
        UUID      pessoaId
    ) {
        this.createdDate = createdDate;
        this.createdUser = createdUser;
        this.updatedDate = updatedDate;
        this.updatedUser = updatedUser;
        this.active = active;
        this.id = id;
        this.vendaDiaId = vendaDiaId;
        this.pessoaId = pessoaId;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public Venda setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UUID getCreatedUser() {
        return this.createdUser;
    }

    public Venda setCreatedUser(UUID createdUser) {
        this.createdUser = createdUser;
        return this;
    }

    public Timestamp getUpdatedDate() {
        return this.updatedDate;
    }

    public Venda setUpdatedDate(Timestamp updatedDate) {
        this.updatedDate = updatedDate;
        return this;
    }

    public UUID getUpdatedUser() {
        return this.updatedUser;
    }

    public Venda setUpdatedUser(UUID updatedUser) {
        this.updatedUser = updatedUser;
        return this;
    }

    public Boolean getActive() {
        return this.active;
    }

    public Venda setActive(Boolean active) {
        this.active = active;
        return this;
    }

    public UUID getId() {
        return this.id;
    }

    public Venda setId(UUID id) {
        this.id = id;
        return this;
    }

    public UUID getVendaDiaId() {
        return this.vendaDiaId;
    }

    public Venda setVendaDiaId(UUID vendaDiaId) {
        this.vendaDiaId = vendaDiaId;
        return this;
    }

    public UUID getPessoaId() {
        return this.pessoaId;
    }

    public Venda setPessoaId(UUID pessoaId) {
        this.pessoaId = pessoaId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Venda (");

        sb.append(createdDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(updatedDate);
        sb.append(", ").append(updatedUser);
        sb.append(", ").append(active);
        sb.append(", ").append(id);
        sb.append(", ").append(vendaDiaId);
        sb.append(", ").append(pessoaId);

        sb.append(")");
        return sb.toString();
    }
}
