/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.tables.Divida;
import br.com.rodrigocardoso.database.tables.records.DividaRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DividaDao extends DAOImpl<DividaRecord, br.com.rodrigocardoso.database.tables.pojos.Divida, UUID> {

    /**
     * Create a new DividaDao without any configuration
     */
    public DividaDao() {
        super(Divida.DIVIDA, br.com.rodrigocardoso.database.tables.pojos.Divida.class);
    }

    /**
     * Create a new DividaDao with an attached configuration
     */
    public DividaDao(Configuration configuration) {
        super(Divida.DIVIDA, br.com.rodrigocardoso.database.tables.pojos.Divida.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.Divida object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByCreatedDate(Timestamp... values) {
        return fetch(Divida.DIVIDA.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByCreatedUser(UUID... values) {
        return fetch(Divida.DIVIDA.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByUpdatedDate(Timestamp... values) {
        return fetch(Divida.DIVIDA.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByUpdatedUser(UUID... values) {
        return fetch(Divida.DIVIDA.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByActive(Boolean... values) {
        return fetch(Divida.DIVIDA.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchById(UUID... values) {
        return fetch(Divida.DIVIDA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.Divida fetchOneById(UUID value) {
        return fetchOne(Divida.DIVIDA.ID, value);
    }

    /**
     * Fetch records that have <code>descricao IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByDescricao(String... values) {
        return fetch(Divida.DIVIDA.DESCRICAO, values);
    }

    /**
     * Fetch records that have <code>valor IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByValor(Double... values) {
        return fetch(Divida.DIVIDA.VALOR, values);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByData(Timestamp... values) {
        return fetch(Divida.DIVIDA.DATA, values);
    }

    /**
     * Fetch records that have <code>pessoa_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Divida> fetchByPessoaId(UUID... values) {
        return fetch(Divida.DIVIDA.PESSOA_ID, values);
    }
}
