/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.tables.Doacao;
import br.com.rodrigocardoso.database.tables.records.DoacaoRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoacaoDao extends DAOImpl<DoacaoRecord, br.com.rodrigocardoso.database.tables.pojos.Doacao, UUID> {

    /**
     * Create a new DoacaoDao without any configuration
     */
    public DoacaoDao() {
        super(Doacao.DOACAO, br.com.rodrigocardoso.database.tables.pojos.Doacao.class);
    }

    /**
     * Create a new DoacaoDao with an attached configuration
     */
    public DoacaoDao(Configuration configuration) {
        super(Doacao.DOACAO, br.com.rodrigocardoso.database.tables.pojos.Doacao.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.Doacao object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByCreatedDate(Timestamp... values) {
        return fetch(Doacao.DOACAO.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByCreatedUser(UUID... values) {
        return fetch(Doacao.DOACAO.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByUpdatedDate(Timestamp... values) {
        return fetch(Doacao.DOACAO.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByUpdatedUser(UUID... values) {
        return fetch(Doacao.DOACAO.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByActive(Boolean... values) {
        return fetch(Doacao.DOACAO.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchById(UUID... values) {
        return fetch(Doacao.DOACAO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.Doacao fetchOneById(UUID value) {
        return fetchOne(Doacao.DOACAO.ID, value);
    }

    /**
     * Fetch records that have <code>descricao IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByDescricao(String... values) {
        return fetch(Doacao.DOACAO.DESCRICAO, values);
    }

    /**
     * Fetch records that have <code>valor IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByValor(Double... values) {
        return fetch(Doacao.DOACAO.VALOR, values);
    }

    /**
     * Fetch records that have <code>pessoa_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByPessoaId(UUID... values) {
        return fetch(Doacao.DOACAO.PESSOA_ID, values);
    }

    /**
     * Fetch records that have <code>venda_dia_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Doacao> fetchByVendaDiaId(UUID... values) {
        return fetch(Doacao.DOACAO.VENDA_DIA_ID, values);
    }
}
