/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.enums.TipoPessoas;
import br.com.rodrigocardoso.database.tables.Pessoa;
import br.com.rodrigocardoso.database.tables.records.PessoaRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PessoaDao extends DAOImpl<PessoaRecord, br.com.rodrigocardoso.database.tables.pojos.Pessoa, UUID> {

    /**
     * Create a new PessoaDao without any configuration
     */
    public PessoaDao() {
        super(Pessoa.PESSOA, br.com.rodrigocardoso.database.tables.pojos.Pessoa.class);
    }

    /**
     * Create a new PessoaDao with an attached configuration
     */
    public PessoaDao(Configuration configuration) {
        super(Pessoa.PESSOA, br.com.rodrigocardoso.database.tables.pojos.Pessoa.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.Pessoa object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByCreatedDate(Timestamp... values) {
        return fetch(Pessoa.PESSOA.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByCreatedUser(UUID... values) {
        return fetch(Pessoa.PESSOA.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByUpdatedDate(Timestamp... values) {
        return fetch(Pessoa.PESSOA.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByUpdatedUser(UUID... values) {
        return fetch(Pessoa.PESSOA.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByActive(Boolean... values) {
        return fetch(Pessoa.PESSOA.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchById(UUID... values) {
        return fetch(Pessoa.PESSOA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.Pessoa fetchOneById(UUID value) {
        return fetchOne(Pessoa.PESSOA.ID, value);
    }

    /**
     * Fetch records that have <code>nome IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByNome(String... values) {
        return fetch(Pessoa.PESSOA.NOME, values);
    }

    /**
     * Fetch records that have <code>telefone IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByTelefone(String... values) {
        return fetch(Pessoa.PESSOA.TELEFONE, values);
    }

    /**
     * Fetch records that have <code>pessoa IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Pessoa> fetchByPessoa(TipoPessoas... values) {
        return fetch(Pessoa.PESSOA.PESSOA_, values);
    }
}
