/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.tables.Produto;
import br.com.rodrigocardoso.database.tables.records.ProdutoRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProdutoDao extends DAOImpl<ProdutoRecord, br.com.rodrigocardoso.database.tables.pojos.Produto, UUID> {

    /**
     * Create a new ProdutoDao without any configuration
     */
    public ProdutoDao() {
        super(Produto.PRODUTO, br.com.rodrigocardoso.database.tables.pojos.Produto.class);
    }

    /**
     * Create a new ProdutoDao with an attached configuration
     */
    public ProdutoDao(Configuration configuration) {
        super(Produto.PRODUTO, br.com.rodrigocardoso.database.tables.pojos.Produto.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.Produto object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByCreatedDate(Timestamp... values) {
        return fetch(Produto.PRODUTO.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByCreatedUser(UUID... values) {
        return fetch(Produto.PRODUTO.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByUpdatedDate(Timestamp... values) {
        return fetch(Produto.PRODUTO.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByUpdatedUser(UUID... values) {
        return fetch(Produto.PRODUTO.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByActive(Boolean... values) {
        return fetch(Produto.PRODUTO.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchById(UUID... values) {
        return fetch(Produto.PRODUTO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.Produto fetchOneById(UUID value) {
        return fetchOne(Produto.PRODUTO.ID, value);
    }

    /**
     * Fetch records that have <code>descricao IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByDescricao(String... values) {
        return fetch(Produto.PRODUTO.DESCRICAO, values);
    }

    /**
     * Fetch records that have <code>codigo IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByCodigo(String... values) {
        return fetch(Produto.PRODUTO.CODIGO, values);
    }

    /**
     * Fetch records that have <code>valor IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByValor(Double... values) {
        return fetch(Produto.PRODUTO.VALOR, values);
    }

    /**
     * Fetch records that have <code>categoria_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.Produto> fetchByCategoriaId(UUID... values) {
        return fetch(Produto.PRODUTO.CATEGORIA_ID, values);
    }
}
