/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.enums.StatusVendaDia;
import br.com.rodrigocardoso.database.tables.VendaDia;
import br.com.rodrigocardoso.database.tables.records.VendaDiaRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaDiaDao extends DAOImpl<VendaDiaRecord, br.com.rodrigocardoso.database.tables.pojos.VendaDia, UUID> {

    /**
     * Create a new VendaDiaDao without any configuration
     */
    public VendaDiaDao() {
        super(VendaDia.VENDA_DIA, br.com.rodrigocardoso.database.tables.pojos.VendaDia.class);
    }

    /**
     * Create a new VendaDiaDao with an attached configuration
     */
    public VendaDiaDao(Configuration configuration) {
        super(VendaDia.VENDA_DIA, br.com.rodrigocardoso.database.tables.pojos.VendaDia.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.VendaDia object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByCreatedDate(Timestamp... values) {
        return fetch(VendaDia.VENDA_DIA.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByCreatedUser(UUID... values) {
        return fetch(VendaDia.VENDA_DIA.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByUpdatedDate(Timestamp... values) {
        return fetch(VendaDia.VENDA_DIA.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByUpdatedUser(UUID... values) {
        return fetch(VendaDia.VENDA_DIA.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByActive(Boolean... values) {
        return fetch(VendaDia.VENDA_DIA.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchById(UUID... values) {
        return fetch(VendaDia.VENDA_DIA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.VendaDia fetchOneById(UUID value) {
        return fetchOne(VendaDia.VENDA_DIA.ID, value);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByData(Timestamp... values) {
        return fetch(VendaDia.VENDA_DIA.DATA, values);
    }

    /**
     * Fetch records that have <code>valor_abertura IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByValorAbertura(Double... values) {
        return fetch(VendaDia.VENDA_DIA.VALOR_ABERTURA, values);
    }

    /**
     * Fetch records that have <code>valor_fechamento IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByValorFechamento(Double... values) {
        return fetch(VendaDia.VENDA_DIA.VALOR_FECHAMENTO, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByStatus(StatusVendaDia... values) {
        return fetch(VendaDia.VENDA_DIA.STATUS, values);
    }

    /**
     * Fetch records that have <code>motivo_cancelamento IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaDia> fetchByMotivoCancelamento(String... values) {
        return fetch(VendaDia.VENDA_DIA.MOTIVO_CANCELAMENTO, values);
    }
}
