/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.daos;


import br.com.rodrigocardoso.database.tables.VendaProduto;
import br.com.rodrigocardoso.database.tables.records.VendaProdutoRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendaProdutoDao extends DAOImpl<VendaProdutoRecord, br.com.rodrigocardoso.database.tables.pojos.VendaProduto, UUID> {

    /**
     * Create a new VendaProdutoDao without any configuration
     */
    public VendaProdutoDao() {
        super(VendaProduto.VENDA_PRODUTO, br.com.rodrigocardoso.database.tables.pojos.VendaProduto.class);
    }

    /**
     * Create a new VendaProdutoDao with an attached configuration
     */
    public VendaProdutoDao(Configuration configuration) {
        super(VendaProduto.VENDA_PRODUTO, br.com.rodrigocardoso.database.tables.pojos.VendaProduto.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(br.com.rodrigocardoso.database.tables.pojos.VendaProduto object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByCreatedDate(Timestamp... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByCreatedUser(UUID... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.CREATED_USER, values);
    }

    /**
     * Fetch records that have <code>updated_date IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByUpdatedDate(Timestamp... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.UPDATED_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_user IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByUpdatedUser(UUID... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.UPDATED_USER, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByActive(Boolean... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchById(UUID... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public br.com.rodrigocardoso.database.tables.pojos.VendaProduto fetchOneById(UUID value) {
        return fetchOne(VendaProduto.VENDA_PRODUTO.ID, value);
    }

    /**
     * Fetch records that have <code>valor_unitario IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByValorUnitario(Double... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.VALOR_UNITARIO, values);
    }

    /**
     * Fetch records that have <code>quantidade IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByQuantidade(Integer... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.QUANTIDADE, values);
    }

    /**
     * Fetch records that have <code>produto_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByProdutoId(UUID... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.PRODUTO_ID, values);
    }

    /**
     * Fetch records that have <code>venda_id IN (values)</code>
     */
    public List<br.com.rodrigocardoso.database.tables.pojos.VendaProduto> fetchByVendaId(UUID... values) {
        return fetch(VendaProduto.VENDA_PRODUTO.VENDA_ID, values);
    }
}
