/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database;


import br.com.rodrigocardoso.database.tables.Categoria;
import br.com.rodrigocardoso.database.tables.Divida;
import br.com.rodrigocardoso.database.tables.Doacao;
import br.com.rodrigocardoso.database.tables.Pagamento;
import br.com.rodrigocardoso.database.tables.PagamentoDivida;
import br.com.rodrigocardoso.database.tables.Pessoa;
import br.com.rodrigocardoso.database.tables.Produto;
import br.com.rodrigocardoso.database.tables.Usuario;
import br.com.rodrigocardoso.database.tables.Venda;
import br.com.rodrigocardoso.database.tables.VendaDia;
import br.com.rodrigocardoso.database.tables.VendaProduto;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORIA_PKEY = Indexes0.CATEGORIA_PKEY;
    public static final Index DIVIDA_PKEY = Indexes0.DIVIDA_PKEY;
    public static final Index DOACAO_PKEY = Indexes0.DOACAO_PKEY;
    public static final Index PAGAMENTO_PKEY = Indexes0.PAGAMENTO_PKEY;
    public static final Index PAGAMENTO_DIVIDA_PKEY = Indexes0.PAGAMENTO_DIVIDA_PKEY;
    public static final Index PESSOA_PKEY = Indexes0.PESSOA_PKEY;
    public static final Index PRODUTO_PKEY = Indexes0.PRODUTO_PKEY;
    public static final Index USUARIO_PKEY = Indexes0.USUARIO_PKEY;
    public static final Index VENDA_PKEY = Indexes0.VENDA_PKEY;
    public static final Index VENDA_DIA_PKEY = Indexes0.VENDA_DIA_PKEY;
    public static final Index VENDA_PRODUTO_PKEY = Indexes0.VENDA_PRODUTO_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CATEGORIA_PKEY = createIndex("categoria_pkey", Categoria.CATEGORIA, new OrderField[] { Categoria.CATEGORIA.ID }, true);
        public static Index DIVIDA_PKEY = createIndex("divida_pkey", Divida.DIVIDA, new OrderField[] { Divida.DIVIDA.ID }, true);
        public static Index DOACAO_PKEY = createIndex("doacao_pkey", Doacao.DOACAO, new OrderField[] { Doacao.DOACAO.ID }, true);
        public static Index PAGAMENTO_PKEY = createIndex("pagamento_pkey", Pagamento.PAGAMENTO, new OrderField[] { Pagamento.PAGAMENTO.ID }, true);
        public static Index PAGAMENTO_DIVIDA_PKEY = createIndex("pagamento_divida_pkey", PagamentoDivida.PAGAMENTO_DIVIDA, new OrderField[] { PagamentoDivida.PAGAMENTO_DIVIDA.ID }, true);
        public static Index PESSOA_PKEY = createIndex("pessoa_pkey", Pessoa.PESSOA, new OrderField[] { Pessoa.PESSOA.ID }, true);
        public static Index PRODUTO_PKEY = createIndex("produto_pkey", Produto.PRODUTO, new OrderField[] { Produto.PRODUTO.ID }, true);
        public static Index USUARIO_PKEY = createIndex("usuario_pkey", Usuario.USUARIO, new OrderField[] { Usuario.USUARIO.ID }, true);
        public static Index VENDA_PKEY = createIndex("venda_pkey", Venda.VENDA, new OrderField[] { Venda.VENDA.ID }, true);
        public static Index VENDA_DIA_PKEY = createIndex("venda_dia_pkey", VendaDia.VENDA_DIA, new OrderField[] { VendaDia.VENDA_DIA.ID }, true);
        public static Index VENDA_PRODUTO_PKEY = createIndex("venda_produto_pkey", VendaProduto.VENDA_PRODUTO, new OrderField[] { VendaProduto.VENDA_PRODUTO.ID }, true);
    }
}
