/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database;


import br.com.rodrigocardoso.database.tables.Categoria;
import br.com.rodrigocardoso.database.tables.Divida;
import br.com.rodrigocardoso.database.tables.Doacao;
import br.com.rodrigocardoso.database.tables.Entidade;
import br.com.rodrigocardoso.database.tables.Pagamento;
import br.com.rodrigocardoso.database.tables.PagamentoDivida;
import br.com.rodrigocardoso.database.tables.Pessoa;
import br.com.rodrigocardoso.database.tables.Produto;
import br.com.rodrigocardoso.database.tables.Usuario;
import br.com.rodrigocardoso.database.tables.Venda;
import br.com.rodrigocardoso.database.tables.VendaDia;
import br.com.rodrigocardoso.database.tables.VendaProduto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1958829307;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.categoria</code>.
     */
    public final Categoria CATEGORIA = br.com.rodrigocardoso.database.tables.Categoria.CATEGORIA;

    /**
     * The table <code>public.divida</code>.
     */
    public final Divida DIVIDA = br.com.rodrigocardoso.database.tables.Divida.DIVIDA;

    /**
     * The table <code>public.doacao</code>.
     */
    public final Doacao DOACAO = br.com.rodrigocardoso.database.tables.Doacao.DOACAO;

    /**
     * The table <code>public.entidade</code>.
     */
    public final Entidade ENTIDADE = br.com.rodrigocardoso.database.tables.Entidade.ENTIDADE;

    /**
     * The table <code>public.pagamento</code>.
     */
    public final Pagamento PAGAMENTO = br.com.rodrigocardoso.database.tables.Pagamento.PAGAMENTO;

    /**
     * The table <code>public.pagamento_divida</code>.
     */
    public final PagamentoDivida PAGAMENTO_DIVIDA = br.com.rodrigocardoso.database.tables.PagamentoDivida.PAGAMENTO_DIVIDA;

    /**
     * The table <code>public.pessoa</code>.
     */
    public final Pessoa PESSOA = br.com.rodrigocardoso.database.tables.Pessoa.PESSOA;

    /**
     * The table <code>public.produto</code>.
     */
    public final Produto PRODUTO = br.com.rodrigocardoso.database.tables.Produto.PRODUTO;

    /**
     * The table <code>public.usuario</code>.
     */
    public final Usuario USUARIO = br.com.rodrigocardoso.database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.venda</code>.
     */
    public final Venda VENDA = br.com.rodrigocardoso.database.tables.Venda.VENDA;

    /**
     * The table <code>public.venda_dia</code>.
     */
    public final VendaDia VENDA_DIA = br.com.rodrigocardoso.database.tables.VendaDia.VENDA_DIA;

    /**
     * The table <code>public.venda_produto</code>.
     */
    public final VendaProduto VENDA_PRODUTO = br.com.rodrigocardoso.database.tables.VendaProduto.VENDA_PRODUTO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Categoria.CATEGORIA,
            Divida.DIVIDA,
            Doacao.DOACAO,
            Entidade.ENTIDADE,
            Pagamento.PAGAMENTO,
            PagamentoDivida.PAGAMENTO_DIVIDA,
            Pessoa.PESSOA,
            Produto.PRODUTO,
            Usuario.USUARIO,
            Venda.VENDA,
            VendaDia.VENDA_DIA,
            VendaProduto.VENDA_PRODUTO);
    }
}
