/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database;


import br.com.rodrigocardoso.database.tables.Categoria;
import br.com.rodrigocardoso.database.tables.Divida;
import br.com.rodrigocardoso.database.tables.Doacao;
import br.com.rodrigocardoso.database.tables.Entidade;
import br.com.rodrigocardoso.database.tables.Pagamento;
import br.com.rodrigocardoso.database.tables.PagamentoDivida;
import br.com.rodrigocardoso.database.tables.Pessoa;
import br.com.rodrigocardoso.database.tables.Produto;
import br.com.rodrigocardoso.database.tables.Usuario;
import br.com.rodrigocardoso.database.tables.Venda;
import br.com.rodrigocardoso.database.tables.VendaDia;
import br.com.rodrigocardoso.database.tables.VendaProduto;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.categoria</code>.
     */
    public static final Categoria CATEGORIA = br.com.rodrigocardoso.database.tables.Categoria.CATEGORIA;

    /**
     * The table <code>public.divida</code>.
     */
    public static final Divida DIVIDA = br.com.rodrigocardoso.database.tables.Divida.DIVIDA;

    /**
     * The table <code>public.doacao</code>.
     */
    public static final Doacao DOACAO = br.com.rodrigocardoso.database.tables.Doacao.DOACAO;

    /**
     * The table <code>public.entidade</code>.
     */
    public static final Entidade ENTIDADE = br.com.rodrigocardoso.database.tables.Entidade.ENTIDADE;

    /**
     * The table <code>public.pagamento</code>.
     */
    public static final Pagamento PAGAMENTO = br.com.rodrigocardoso.database.tables.Pagamento.PAGAMENTO;

    /**
     * The table <code>public.pagamento_divida</code>.
     */
    public static final PagamentoDivida PAGAMENTO_DIVIDA = br.com.rodrigocardoso.database.tables.PagamentoDivida.PAGAMENTO_DIVIDA;

    /**
     * The table <code>public.pessoa</code>.
     */
    public static final Pessoa PESSOA = br.com.rodrigocardoso.database.tables.Pessoa.PESSOA;

    /**
     * The table <code>public.produto</code>.
     */
    public static final Produto PRODUTO = br.com.rodrigocardoso.database.tables.Produto.PRODUTO;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = br.com.rodrigocardoso.database.tables.Usuario.USUARIO;

    /**
     * The table <code>public.venda</code>.
     */
    public static final Venda VENDA = br.com.rodrigocardoso.database.tables.Venda.VENDA;

    /**
     * The table <code>public.venda_dia</code>.
     */
    public static final VendaDia VENDA_DIA = br.com.rodrigocardoso.database.tables.VendaDia.VENDA_DIA;

    /**
     * The table <code>public.venda_produto</code>.
     */
    public static final VendaProduto VENDA_PRODUTO = br.com.rodrigocardoso.database.tables.VendaProduto.VENDA_PRODUTO;
}
